### ISSUE TITLE
Shopping_item_card_list ads are still showing in YouTube

### ISSUE THREAD

**Issue by quoctrile8** [PoomSmart/YouTube-X#14]
Hello PoomSmart, I still get shopping ads in YouTube homepage and while scrolling other videos suggestions
YouTube version: 19.26.5
YouTube-X version: 1.7.4
![image](https://github.com/user-attachments/assets/4b4698da-f155-43cb-836e-867250f2eca8)
![image](https://github.com/user-attachments/assets/517c0fbd-f874-44fc-bab3-ad94f562041b)

**Comment by oldman20** [comment]
@quoctrile8 pls teach me how to use this repo for build?

**Comment by LaxusiC** [comment]
@PoomSmart Please release the better block ads for Shorts update on your repo

**Comment by PoomSmart** [comment]
Should be fixed in v1.7.5

**Comment by quoctrile8** [comment]
Hello PoomSmart, after updating the tweak to ver 1.7.5, the shopping ads still exist.
YouTube version: 19.45.4
YouTube X version: 1.7.5
![image](https://github.com/user-attachments/assets/5e70637a-572c-4ea7-af20-8e58d95c0ad7)

**Comment by cameren2k** [comment]
> Hello PoomSmart, after updating the tweak to ver 1.7.5, the shopping ads still exist.
> YouTube version: 19.45.4
> YouTube X version: 1.7.5
> ![image](https://github.com/user-attachments/assets/5e70637a-572c-4ea7-af20-8e58d95c0ad7)

also tried this fix, still seeing products as well ![image](https://github.com/user-attachments/assets/66121124-7a5c-4102-95cf-17fd8d92e1dd)

**Comment by PoomSmart** [comment]
What's the ID of this ad, shopping_item_card_list ?

**Comment by cameren2k** [comment]
> What's the ID of this ad, shopping_item_card_list ?

i see a eml.expandable_metadata.vpp , unsure if that's the correct thing to look for

**Comment by quoctrile8** [comment]
> What's the ID of this ad, shopping_item_card_list ?

I see it is an id.styled_product_carousel_item.view
![image](https://github.com/user-attachments/assets/0e569362-21da-48dc-9861-7f0954f9c3d3)

**Comment by PoomSmart** [comment]
YouTube-X would have already blocked `eml.expandable_metadata.vpp` and `styled_product_carousel_item` based on the code. It's weird that it doesn't work. I don't see the ads myself, maybe its due to geolocation?

**Comment by quoctrile8** [comment]
> YouTube-X would have already blocked `eml.expandable_metadata.vpp` and `styled_product_carousel_item` based on the code. It's weird that it doesn't work. I don't see the ads myself, maybe its due to geolocation?

You're right. After I use VPN to change geolocation from Vietnam to Japan and restart YouTube, the ads disappear.
So may I ask if there is a way to fake geolocation for YouTube but not using VPN in order to hide ads?

**Comment by PoomSmart** [comment]
Can you try this code?

```
%hook _ASDisplayView

- (void)didMoveToWindow {
    %orig;
    if (([self.accessibilityIdentifier isEqualToString:@"eml.expandable_metadata.vpp"]))
        [self removeFromSuperview];
}

%end
```

**Comment by quoctrile8** [comment]
> Can you try this code?
> 
> 
> 
> ```
> 
> %hook _ASDisplayView
> 
> 
> 
> - (void)didMoveToWindow {
> 
>     %orig;
> 
>     if (([self.accessibilityIdentifier isEqualToString:@"eml.expandable_metadata.vpp"]))
> 
>         [self removeFromSuperview];
> 
> }
> 
> 
> 
> %end
> 
> ```

I'm sorry but I don't know how to build debs.
Could you provide me with the .deb file so I can test it?

**Comment by PoomSmart** [comment]
[com.ps.ytx_1.7.5_iphoneos-arm64.deb.zip](https://github.com/user-attachments/files/17801255/com.ps.ytx_1.7.5_iphoneos-arm64.deb.zip)

@quoctrile8

**Comment by quoctrile8** [comment]
> [com.ps.ytx_1.7.5_iphoneos-arm64.deb.zip](https://github.com/user-attachments/files/17801255/com.ps.ytx_1.7.5_iphoneos-arm64.deb.zip)
> 
> 
> 
> @quoctrile8 

It's working well. Thank you so much.

**Comment by PoomSmart** [comment]
Thanks for testing. I will roll out the new version in few days.

**Comment by oldman20** [comment]
i tried inject above deb with https://github.com/PoomSmart/YouPiP it work but cant login, "You can't sign in to this app because Google can't confirm that this app is secure."

**Comment by PoomSmart** [comment]
@quoctrile8 
Released v1.7.6
